#!/usr/bin/env python3
"""Regenerate the '## Address map' tables in the product's games document
(docs/games_applications.md by default) from its symbol map and notes JSON.

Usage: games_doc_tables.py [--check]   (--check exits 1 when the document is stale)
"""
import csv, json, re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import games_product as P

DOC = P.path("doc")
GROUPS_3210 = [
    ("Snake", ("snake_",)), ("Memory", ("memory_",)), ("Rotation", ("rotation_",)),
    ("Fourth table entry (game3)", ("game3_",)), ("Logic (undispatched)", ("logic_",)),
    ("Games framework and plugin table", ("game_", "games_")),
    ("Widget layer", ("widget_", "ui_")), ("Menu framework", ("menu_",)),
    ("Runtime services used by the games", ("rand_", "srand_", "rtos_", "lcd_", "str", "isdigit", "atoi", "utoa", "memcpy", "int_to", "double_", "divmod", "sched_delay_cancel", "periodic_", "ctype")),
]
GROUPS_3310 = [
    ("Space Impact", ("si_",)),
    ("Snake II (games_snake2_3310.md)", ("snake2_",)),
    ("Bantumi (games_bantumi_3310.md)", ("bantumi_",)),
    ("Pairs II (games_pairs2_3310.md)", ("pairs2_",)),
    ("Games framework", ("game_", "games_", "title_", "done_tick_")),
    ("Main menu", ("menu_",)),
    ("Sprite and tilemap engine", ("sprite_", "tilemap_")),
    ("Runtime services used by the games", ("rand_", "rt_", "memcpy", "memset", "timer_", "heap_", "sound_", "vibra", "charger_")),
]
GROUPS = {"3210": GROUPS_3210, "3310": GROUPS_3310}[P.name()]
BEGIN = "<!-- address map: generated by tools/games_doc_tables.py -->"
END = "<!-- end address map -->"

def render():
    names = {}
    for r in csv.reader(open(P.path("symbols"))):
        if r and r[0] != "address": names[int(r[0], 16)] = (r[1], r[2])
    notes = {int(b["addr"], 16): b["lines"] for b in json.load(open(P.path("notes")))["blocks"]}
    out, seen = [BEGIN], set()
    for title, prefixes in GROUPS:
        rows = [(a, k, n) for a, (k, n) in sorted(names.items()) if n.startswith(prefixes) and a not in seen]
        if not rows: continue
        out.append(f"\n### {title}\n\n| Address | Kind | Name | Evidence |\n|---|---|---|---|")
        for a, k, n in rows:
            seen.add(a); ev = " ".join(notes.get(a, [""]))[:300].replace("|", "\\|")
            out.append(f"| `0x{a:06x}` | {k} | `{n}` | {ev} |")
    out.append("\n" + END)
    return "\n".join(out)

def main():
    doc = DOC.read_text()
    new = render()
    updated = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda m: new, doc, flags=re.S)
    if "--check" in sys.argv:
        sys.exit(0 if updated == doc else 1)
    DOC.write_text(updated); print("address map regenerated")

if __name__ == "__main__":
    main()
